force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Show_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_Time__c</fullName>
    <label>Show Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ShowTimeInLWc.cls
public class ShowTimeInLWc {
    
    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProject()
    {
        List<Project__c> plist = new List<Project__c>();
        try{
          plist=[select Id,Show_Time__c, Name FROM Project__c];
          System.debug('plist:'+plist);
            
        }catch(Exception ex){
            System.debug('Error:'+ex.getMessage());
            
        }
        return plist;
    }
    
}