force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectTest.cls
public class ProjectTest {

     @AuraEnabled 
     public static list<Project__c> fetchProject(){
     List<Project__c> plist= [SELECT Id,Name From Project__c limit 5];
     return plist;
     }
         
      @AuraEnabled 
     public static list<Tower__c> fetchTower(String Pid)
     {
   	    system.debug('Id'+Pid);
        List<Tower__c> tlist=[select Id, Name From Tower__c WHERE Project__r.id =: Pid];
        system.debug('after query '+tlist);
        return tlist;        
    }
}