force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Stamp_Duty_Registration__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty_Registration__c</fullName>
    <label>Stamp Duty &amp; Registration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Agreement_Value__c  +  GST_Amount__c  +  Stamp_Duty_Registration__c  +  Other_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Print_Quotation.cls
public class Print_Quotation {
        public Id QID {get;set;}
        public Quotation__c  Qlist {get;set;}
    
    public Print_Quotation()
    {
          String QID = apexpages.currentPage().getparameters().get('QId');
          if(QId != null)
          {
              Qlist= [Select id,Name ,Agreement_Value__c ,Date__c ,GST_Amount__c ,Stamp_Duty_Registration__c ,
                      Other_Charges__c ,Total_Amount__c	from Quotation__c where Id=: QID];
          }

    }


}